name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pyflakes Syntax Checker
      uses: lgeiger/pyflakes-action@v1.0.1
    - name: python-lint
      uses: CyberZHG/github-action-python-lint@0.0.2
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
